// User reducer types

export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const SET_USER_IMAGE = "SET_USER_IMAGE";
export const GET_USER_MESSAGES = "GET_USER_MESSAGES";
export const GET_ALL_USERS = "GET_ALL_USERS";
