// User reducer types

export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const GET_BEERS = "GET_BEERS";
export const SET_LOADING = "SET_LOADING";
export const SET_RANDOM_BEERS = "SET_RANDOM_BEERS";
export const SORT_MY_BEERS = "SORT_MY_BEERS";
export const SET_SORT_TYPE = "SET_SORT_TYPE";
export const SET_SEARCH_SORT_TYPE = "SET_SEARCH_SORT_TYPE";
export const SORT_SEARCH_RESULTS = "SORT_SEARCH_RESULTS";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SET_COLOR_SCHEME = "SET_COLOR_SCHEME";
export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const RESET_EMAIL_MESSAGE = "RESET_EMAIL_MESSAGE";
export const LOGOUT = "LOGOUT";
export const LOADING_USER = "LOADING_USER";
export const SET_USER_IMAGE = "SET_USER_IMAGE";
export const GET_USER_MESSAGES = "GET_USER_MESSAGES";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const SHOW_MODAL = "SHOW_MODAL";
